- hosts: all
  tasks:
    - name: "Install apt-transport-https"
      apt:
        name: ['apt-transport-https']
        state: latest
    - name: "Install ca-certificatess"
      apt:
        name: ['ca-certificates']
        state: latest
    - name: "Install curl"
      apt:
        name: ['curl']
        state: latest
    - name: "Install software-properties-common"
      apt:
        name: ['software-properties-common']
        state: latest
