- hosts: all
  tasks:
    - name: "Install apt-transport-https"
      apt:
        name: ['apt-transport-https']
        state: latest
    - name: "Install ca-certificatess"
      apt:
        name: ['ca-certificates']
        state: latest
    - name: "Install curl"
      apt:
        name: ['curl']
        state: latest
    - name: "Install software-properties-common"
      apt:
        name: ['software-properties-common']
        state: latest
        
    - name: "Get GPG I"
      shell: mkdir -p /etc/apt/keyrings
      
    - name: "Get GPG II"
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      
    - name: "Add Repository"
      shell:  add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable\"
      
    - name: "Update packages"
      apt:
        update_cache: yes
        
    - name: "Install Docker"
      apt:
          name: ['docker-ce']
          state: latest

